pipeline {
    agent any

    parameters {
        choice(name: 'TEST_TYPE', choices: ['api', 'ui', 'all'], description: 'Select test type')
        choice(name: 'BROWSER', choices: ['chromium', 'firefox', 'webkit'], description: 'Select browser')
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                url: 'YOUR_GITHUB_URL'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    npm install
                    npx playwright install
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    cd backend
                    JENKINS_NODE_COOKIE=dontKillMe nohup node server.js > server.log 2>&1 &
                    sleep 5
                    cd ..

                    if [ "$TEST_TYPE" = "api" ]; then
                        npx playwright test tests/api --project=$BROWSER --workers=1
                    elif [ "$TEST_TYPE" = "ui" ]; then
                        npx playwright test tests/ui --project=$BROWSER --workers=1
                    else
                        npx playwright test --project=$BROWSER --workers=1
                    fi
                '''
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'playwright-report/**', allowEmptyArchive: true

            publishHTML([
                allowMissing: true,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'playwright-report',
                reportFiles: 'index.html',
                reportName: 'Playwright Report'
            ])
        }
    }
}