pipeline {
    agent any

    environment {
        PATH = "/usr/local/bin:${env.PATH}"
    }
parameters {
    choice(name: 'TEST_TYPE', choices: ['api', 'ui', 'all'], description: 'Select test type')
    choice(name: 'BROWSER', choices: ['chromium', 'firefox', 'webkit'], description: 'Select browser')
}
    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                url: 'https://github.com/annikasu8/playwright-banking-tests.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    rm -rf node_modules package-lock.json
                    npm install
                    npm install -D @playwright/test
                '''
            }
        }

        stage('Install Playwright Browsers') {
            steps {
                sh 'npx playwright install chromium'
            }
        }

        stage('Run API Tests') {
            steps {
                sh '''
                    cd backend
                    JENKINS_NODE_COOKIE=dontKillMe nohup node server.js > server.log 2>&1 &
                    sleep 5
                    cd ..

                    npx playwright test tests/api --workers=4
                '''
            }
        }
stage('Run UI Tests') {
            steps {
                sh '''
                    cd backend
                    JENKINS_NODE_COOKIE=dontKillMe nohup node server.js > server.log 2>&1 &
                    sleep 5
                    cd ..

                    npx playwright test tests/ui --headed --workers=4
                '''
            }
        }
        stage('Run Tests') {
    steps {
        sh '''
            cd backend
            JENKINS_NODE_COOKIE=dontKillMe nohup node server.js > server.log 2>&1 &
            sleep 5
            cd ..

            if [ "$TEST_TYPE" = "api" ]; then
                npx playwright test tests/api --project=$BROWSER --workers=1
            elif [ "$TEST_TYPE" = "ui" ]; then
                npx playwright test tests/ui --project=$BROWSER --workers=1
            else
                npx playwright test --project=$BROWSER --workers=1
            fi
        '''
    }
}
        stage('Generate HTML Report') {
            steps {
                sh 'npx playwright show-report --host 0.0.0.0 &'
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed!'
        }

        success {
            echo '✅ All tests passed!'
        }

        failure {
            echo '❌ Some tests failed.'
        }
    }
}